name: Flutter CI

on:
  push:
    branches: [ master, actions]
  pull_request:
    branches: [ master ]

jobs:
  android-integration-test:
    name: Android
    runs-on: macOS-latest
    strategy:
      matrix:
        device:
          - "pixel_xl"
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.4'
          channel: 'stable'
      - name: run tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          api-level: 29
          profile: ${{ matrix.device }}
          script: |
            cd ./example/image_classification && flutter pub get
            cd ./example/image_classification && flutter driver --driver='test_driver/image_classification_e2e_test.dart' test/image_classification_e2e.dart
